### ISSUE TITLE
Error occurred

### ISSUE THREAD

**Issue by eiryu** [r7kamura/serverkit#9]
```
$ serverkit check recipe.yml 
/Library/Ruby/Gems/2.0.0/gems/serverkit-0.6.2/lib/serverkit/loaders/base_loader.rb:52:in ``': No such file or directory - recipe.yml (Errno::ENOENT)
    from /Library/Ruby/Gems/2.0.0/gems/serverkit-0.6.2/lib/serverkit/loaders/base_loader.rb:52:in `execute'
    from /Library/Ruby/Gems/2.0.0/gems/serverkit-0.6.2/lib/serverkit/loaders/base_loader.rb:124:in `load_data_from_executable'
    from /Library/Ruby/Gems/2.0.0/gems/serverkit-0.6.2/lib/serverkit/loaders/base_loader.rb:95:in `load_data'
    from /Library/Ruby/Gems/2.0.0/gems/serverkit-0.6.2/lib/serverkit/loaders/recipe_loader.rb:36:in `load_from_data'
    from /Library/Ruby/Gems/2.0.0/gems/serverkit-0.6.2/lib/serverkit/loaders/base_loader.rb:27:in `load'
    from /Library/Ruby/Gems/2.0.0/gems/serverkit-0.6.2/lib/serverkit/actions/base.rb:77:in `recipe'
    from /Library/Ruby/Gems/2.0.0/gems/serverkit-0.6.2/lib/serverkit/actions/base.rb:72:in `setup'
    from /Library/Ruby/Gems/2.0.0/gems/serverkit-0.6.2/lib/serverkit/actions/base.rb:29:in `call'
    from /Library/Ruby/Gems/2.0.0/gems/serverkit-0.6.2/lib/serverkit/command.rb:87:in `check'
    from /Library/Ruby/Gems/2.0.0/gems/serverkit-0.6.2/lib/serverkit/command.rb:46:in `call'
    from /Library/Ruby/Gems/2.0.0/gems/serverkit-0.6.2/bin/serverkit:6:in `<top (required)>'
    from /usr/bin/serverkit:23:in `load'
    from /usr/bin/serverkit:23:in `<main>'
```

recipe.yml

```
resources:
  - type: package
    name: mysql
  - type: package
    name: redis
```
## environment

case1

```
OS X Yosemite 10.10.3
Serverkit installed by bundler

$ ruby -v
ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]

$ gem -v
2.4.5
```

case2

```
OS X Yosemite 10.10.3
Serverkit installed by gem

$ ruby -v
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14]

$ gem -v
2.4.8
```

**Comment by eiryu** [comment]
😭

**Comment by r7kamura** [comment]
:weary:
